# Generated by Django 4.0.1 on 2023-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='log',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
